### ISSUE TITLE
Need tag 0.0.2 on efe8ed780c4db35b958519129b3183d7cdaf120b

### ISSUE THREAD

**Issue by erikeverts** [peimanja/amtoolcm-github-actions#2]
efe8ed780c4db35b958519129b3183d7cdaf120b merged a fix for unauthenticated git calls over git://
No tag was created for version 0.0.2 on this merge so the action with the fix can't be used yet

**Comment by peimanja** [comment]
Thanks for the reminder https://github.com/peimanja/amtoolcm-github-actions/releases/tag/v0.0.2
